---
- project:
    templates:
      - build-openstack-docs-pti
    check:
      jobs:
        - build-openstack-api-ref
        - build-openstack-releasenotes
        - openstack-tox-pep8
        - openstack-tox-linters
        - stx-devstack-ha:
            voting: false
    gate:
      jobs:
        - build-openstack-api-ref
        - build-openstack-releasenotes
        - openstack-tox-pep8
        - openstack-tox-linters
    post:
      jobs:
        - publish-stx-api-ref
        - publish-stx-tox
        - publish-stx-releasenotes

- job:
    name: stx-devstack-ha
    parent: stx-devstack-base
    timeout: 7800
    required-projects:
      - openstack/stx-fault
    vars:
      tox_envlist: functional
      devstack_services:
        horizon: false
        # StarlingX services
        sm-common: true
        sm-db: true
        sm-daemon: true
        sm-client: true
        sm-tools: true
        sm-api: true
        mysql: false
        postgresql: true
        tls-proxy: false
      devstack_plugins:
        stx-ha: git://git.starlingx.io/stx-ha
        stx-fault: git://git.starlingx.io/stx-fault
    files:
      - ^devstack/.*
