---
- project:
    templates:
      - build-openstack-docs-pti
    check:
      jobs:
        - build-openstack-api-ref
        - build-openstack-releasenotes
        - flock-devstack-ha
        - openstack-tox-pep8
        - openstack-tox-linters
    gate:
      jobs:
        - build-openstack-api-ref
        - build-openstack-releasenotes
        - flock-devstack-ha
        - openstack-tox-pep8
        - openstack-tox-linters
    post:
      jobs:
        - publish-stx-api-ref
        - publish-stx-tox
        - publish-stx-releasenotes

- job:
    name: flock-devstack-ha
    parent: flock-devstack-base
    required-projects:
      - openstack/stx-config
      - openstack/stx-fault
      - openstack/stx-integ
      - openstack/stx-metal
      - openstack/stx-nfv
      - openstack/stx-update
    vars:
      tox_envlist: functional
      devstack_services:
        # StarlingX services
        fm-common: true
        fm-api: true
        sm-common: true
        sm-db: true
        sm-daemon: true
        sm-client: true
        sm-tools: true
        sm-api: true
        mysql: false
        postgresql: true
        tls-proxy: false
      devstack_plugins:
        stx-config: https://git.starlingx.io/stx-config
        stx-fault: https:://git.starlingx.io/stx-fault
        stx-ha: https://git.starlingx.io/stx-ha
        stx-integ: https://git.starlingx.io/stx-integ
        stx-metal: https:://git.starlingx.io/stx-metal
        stx-nfv: https:://git.starlingx.io/stx-nfv
        stx-update: https:://git.starlingx.io/stx-update
