---
- project:
    templates:
      - build-openstack-docs-pti
    check:
      jobs:
        - build-openstack-api-ref
        - build-openstack-releasenotes
        - openstack-tox-pep8:
            voting: false
        - openstack-tox-linters
    gate:
      jobs:
        - build-openstack-api-ref
        - build-openstack-releasenotes
        - openstack-tox-linters
    post:
      jobs:
        - publish-stx-tox
