---
- project:
    templates:
      - build-openstack-docs-pti
    check:
      jobs:
        - openstack-tox-pep8:
            voting: false
        - openstack-tox-linters
    gate:
      jobs:
        - openstack-tox-linters
