#!/bin/bash
# Devstack settings

# Services
sm-api
sm-client
sm-common
sm-daemon
sm-db
sm-tools

# Defaults
# --------

STX_HA_NAME=stx-ha

######### Plugin Specific ##########
enable_service $STX_HA_NAME

# This must not use any variables to work properly in the devstack playbook
define_plugin stx-ha
# This works for Zuul jobs using OpenStack's DevStack roles
plugin_requires stx-ha stx-metal
plugin_requires stx-ha stx-config

# Initial source of lib script
source $DEST/stx-ha/devstack/lib/stx-ha
