#
## SPDX-License-Identifier: Apache-2.0
#

install:
	install -d ${DEST_DIR}/var/lib/sm
	install -d ${DEST_DIR}/var/lib/sm/patches
	install sm.hb.db ${DEST_DIR}/var/lib/sm
	install sm.db ${DEST_DIR}/var/lib/sm
	install -m 644 sm-patch.sql ${DEST_DIR}/var/lib/sm/patches

