#
# Copyright (c) 2014 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
build:
	@(cd src; make build )

install:
	@(cd src; make $@)
	@(cd scripts; make $@)

clean:
	@( cd src; make clean )
